# Permalinks
permalink:           pretty

# Setup
title:               hal9k2 blog
tagline:             learn security 
url:                 
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              hal9k2
  url:               https://twitter.com/hal9k2pl
  email:             hal9k2@hotmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/hal9k2/hal9k2.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page list
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
